### ISSUE TITLE
Twitter Cover Photo ugly on project page, but no obvious way to change it :-(

### ISSUE THREAD

**Issue by GriffGreen** [dev-protocol/stakes.social#1059]
Related to #815 and #768

https://stakes.social/0xFa38Fc50e055CBE88Bd569eddCcE057999B2BC9C

BOOOOO! 

I want to tweet our page... but can't cause the picture is ugly :-(

and i don't see a way to change it... I assumed the picture was from twitter so we changed our cover photo there... but it didn't change :-(

maybe you can help ?

I added the example of our new twitter cover pic... It would be awesome if i could just upload it myself... but i can't find a way.

![CS Logo 1500x500](https://user-images.githubusercontent.com/14945613/109809144-40a4a480-7c28-11eb-8497-c84844ad843e.jpeg)

The Commons Stack is more aligned with your vision than you can dream... once we have this bug fixed... We will be shilling your system all over the place!

**Comment by GriffGreen** [comment]
FIXED! Thank you!! :-D

**Comment by talentlessguy** [comment]
> FIXED! Thank you!! :-D

then worth closing?

**Comment by hhatto** [comment]
A while ago, it became possible to edit property information if you are the author, so you can change the cover image yourself.
This issue is closed.

edit button:
<img width="974" alt="edit-button" src="https://user-images.githubusercontent.com/150309/115993125-5cb33980-a60c-11eb-9b00-50dc08bf1b1a.png">
