### ISSUE TITLE
Exclude the 5% fee from creator's rewards shown

### ISSUE THREAD

**Issue by yumemayu** [dev-protocol/stakes.social#1072]
Currently, the creator reward shows 100% of the total creator rewards (property token holders) amount. This can lead to an incorrect amount of withdrawable funds.

- fees should be excluded from creator's reward area.  
- Or separately show the amount available for withdrawal? (This might be work for [DIP38](https://github.com/dev-protocol/DIPs/pull/38))

![Screen_Shot_2021-03-04_at_12 25 47](https://user-images.githubusercontent.com/33956553/110260828-2df7ea00-7ff1-11eb-9a49-e8ed1a52f0cf.png)

**Comment by defi-er** [comment]
The issue is not that the withdrawable amount is incorrect, but that the user doesn't understand why withdraw is less than total rewards. 

Reasons:
1) 5% Treasury fee
2) OSS token is shared amongst contributors
3) Total Rewards is cumulative and doesn't equal to "Available Rewards to be Withdrawn"

Technical Implementation Idea:

1) When withdrawing explicitly show available rewards to withdraw based on wallet and explain why it's less than Total Rewards.

Comment: Stas and I will improve this in the upcoming SSV4 design

2) Add a withdrawable funds section which is based on how much OSS tokens a user holds.
