### ISSUE TITLE
Tokenization hangs at "now tokenizing"

### ISSUE THREAD

**Issue by phryneas** [dev-protocol/stakes.social#1352]
Hi there :wave: 

I am failing at the tokenization step.

I've tried this in Firefox, Chromium 87 and Chromium 91 and waited between 30 minutes or an hour each.

I click on "Tokenize", I sign a message in MetaMask and nothing happens beyond that point.

Is this a bug or am I doing anything inherently wrong?

One thing that might be a factor (but I guess I'd end up in an error in MetaMask?) is that my account currently only has ~0.01 ETH - but given the current gas prices I was told that should be more than enough.

![image](https://user-images.githubusercontent.com/4282439/120387142-d1734500-c329-11eb-85fd-1f28ce5be1f9.png)

**Comment by aggre** [comment]
Thank you for your issue report.

The problem seems to be in the front-end code, as the tokenize transaction you seem to be requesting does not seem to reach the Ethereum network. However, I have not been able to identify the cause of the problem.

Instead, I changed the code to display some additional error messages, and those changes have already been deployed. So can you please try again with the same information?

If you don't even get a new error message, you can also use the Ethereum console called Etherscan instead of Stakes.social to complete the tokenization process manually. Let me know your wallet address, and we can explain the manual process to you.

## About gas fees
Even if you only have 0 ETH, MetaMask should open a second dialog asking you for permission to send a tokenization transaction.
Therefore, page hanging is not dependent on your ETH balance.

However, 0.01 ETH is probably not enough to complete the tokenization process.
The level of gas fees will vary depending on the congestion of the Ethereum network. At the current level, I think you need about 0.0436 ETH. But Ethereum will often return about 20~40% of that amount to you unused.
This is because it is difficult to predict in advance the exact computing resources required for an Ethereum transaction. Hence, a wallet asks for slightly more gas money but returns the unused portion to you.

Gas fees are necessary to support the decentralized computing of the Ethereum network, but we apologize that this is a complicated issue for beginners.

**Comment by phryneas** [comment]
This time it just worked!

Thank you for your support - I am sure those new error messages will come very handy for the next person facing these problems :heart:
