### ISSUE TITLE
[BUG] Your Pools page empty when switching to L2 despite having receivable amounts in a pool.

### ISSUE THREAD

**Issue by phryneas** [dev-protocol/stakes.social#1999]
### Description

I recreated the [Redux Devtools Pool (eth)](https://stakes.social/ethereum/0xB96cBb406F8Eb2712eD8A9055e285E28fd076548)  on [Arbitrum One](https://stakes.social/arbitrum-one/0xB96cBb406F8Eb2712eD8A9055e285E28fd076548) and when I switch between the networks, I can see that I have a Creator Reward/Receivable Amount. 

But when I go to to the "Portfolio" site, the "Your Pools" list is empty when on Arbitrum - everything is just fine when I'm on Etherium.

Is withdrawing DEV not supported at the moment for L2?

Using Chromium with Metamask extension.

### Expected behavior/contents

I see the pool in "portfolio" and can receive Dev, even on ARB.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
@phryneas Hi! Thanks for reporting the bug.

"Your Pools" on the Profile page depends on GraphQL, and this problem occurs because GraphQL cannot be used with Arbitrum.

The community has deprecated GraphQL, and a new set of APIs called "Agent APIs" is being developed in the Dev Kit to replace GraphQL, so we will replace the "Your Pools" implementation with Agent APIs in the future.

You can now use Arbiscan to manually withdraw the rewards:
1. Access to https://arbiscan.io/address/0x1c2699e43F0Bc47b45F27BFc84e99c64851A4BF0#writeProxyContract
2. Scroll down to the "withdraw" section ![image](https://user-images.githubusercontent.com/1970283/148883889-8818c89f-a874-4e8f-a982-cc5413829b7b.png)
3. Enter the address of the Property (tokenized OSS)
4. Click "Write"
