### ISSUE TITLE
Front-page should not show a "Stake" button on my own projects

### ISSUE THREAD

**Issue by sindresorhus** [dev-protocol/stakes.social#814]
https://stakes.social/, it shows "chalk" with a "Stake" button in the box, but I'm the author, so I should not be encouraged to stake my own project.

**Comment by aggre** [comment]
I agree because this is a confusing feature. It requires handling that `AssetItemOnList` does.

https://github.com/dev-protocol/stakes.social/blob/68f4ac710c81578687c1fb39efb902455662e4e8/packages/web/src/components/molecules/AssetItemOnList/index.tsx#L107

https://github.com/dev-protocol/stakes.social/blob/68f4ac710c81578687c1fb39efb902455662e4e8/packages/web/src/components/molecules/AssetItemOnList/index.tsx#L133-L137
